version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /Users/${USER}/Library/Caches/com.apple.findmy.fmipcore/:/findmy
    environment:
      - TMA_PATH=/findmy
      - TMA_DATABASE_DSN=postgresql://postgres:postgres@postgres:5432/findmy
      - TMA_WHITELIST=${TMA_WHITELIST}

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=findmy
    volumes:
      - ./db:/var/lib/postgresql/data
